Add a packaging badge
peak/s5cmd pull request #439
Opened 2022-04-23 09:48 UTC by ehaupt

Add a repology badge showing the packaging status

2022-05-19 13:22 UTC, ilkinulas approved these changes

2022-07-14 20:02 UTC, ilkinulas commented
@sonmezonur could you please take a look at this?

2022-07-24 20:19 UTC, ilkinulas requested changes
Hello @ehaupt, could you please move the badge to the [Unofficial Releases (by Community)](https://github.com/peak/s5cmd/#unofficial-releases-by-community) section ?

We have just created a section in README for these kind of contributions.

Thank you.

2022-07-25 06:59 UTC, ehaupt commented
> Hello @ehaupt, could you please move the badge to the [Unofficial Releases (by Community)](https://github.com/peak/s5cmd/#unofficial-releases-by-community) section ?

Sure thing! Done.

2022-07-25 10:37 UTC, ilkinulas approved these changes

2022-07-25 10:37 UTC, sonmezonur approved these changes

2022-07-25 10:38 UTC, merged